### ISSUE TITLE
Make sure this configuration can be run multiple times

### ISSUE THREAD

**Issue by ryaninvents** [ryaninvents/terraform-node-pm2#1]
In the README:

> If you run this configuration more than once, it might cause the instance to attempt to run multiple copies of the HTTP server on the same port, which it can't do. I'm working on that.

**Todo:**
- [x] Figure out how to check if pm2 is already running a script with a given name
- [x] If a script is already running with the same name, don't start a new one
- [x] Update the README

**Comment by ryaninvents** [comment]
If I set things up with the [process file](http://pm2.keymetrics.io/docs/usage/application-declaration/#json-format) then I won't have to worry about multiple instances. Even better, I might be able to modify this process file from other Terraform configs (maybe with some `jq` magic?), making it easy to use pm2's cluster functionality to deploy multiple applications on the same machine or set of machines.
