### ISSUE TITLE
Enable adding other applications

### ISSUE THREAD

**Issue by ryaninvents** [ryaninvents/terraform-node-pm2#5]
Add a second [Terraform module](https://www.terraform.io/docs/configuration/modules.html) that would allow for a second application to be started via a reference to the [remote state](https://www.terraform.io/docs/providers/terraform/d/remote_state.html).

Usage might look something like this:

```hcl
data "terraform_remote_state" "dev" {
  backend = "s3"
  config {
    bucket = "myterraformstate.example.com"
    region = "us-east-1"
    key = "applications/app-name/deployments/dev/terraform.tfstate"
  }
}

module "second_app" {
  source = "github.com/r24y/terraform-node-pm2/config/application"
  ssh_key = "${data.terraform_remote_state.dev.ssh_key}"
  host = "${data.terraform_remote_state.dev.instance_ip}"
  app {
    name = "my-second-app"
    source_tarball = "${file("${path.cwd}/dist/app.tgz")}"
    config = {
      env = {
        NODE_ENV = "development"
        PORT = 3001
      }
    }
  }
}
```

**Todo:**
- [x] Move `config/terraform` to `config/infrastructure`
- [x] Figure out how to perform idempotent updates to `ecosystem.config.json`
- [ ] Implement `config/application` module
- [ ] Convert sample application to use new module (instead of deploying inline with `config/infrastructure` module
- [ ] Update README
- [ ] Verify deployment of a second application
